### ISSUE TITLE
Crash when taking a screenshot

### ISSUE THREAD

**Issue by qdii** [gabm/satty#1]
Hey! I tried your tool but it crashed for me

```
$ grim -g "$(slurp -o -c '#ff0000ff')" - | satty --filename - --fullscreen --output-filename foo.png
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:70:68
stack backtrace:
   0:     0x55c97aeaade1 - <unknown>
   1:     0x55c97aecd25f - <unknown>
   2:     0x55c97aea89a1 - <unknown>
   3:     0x55c97aeaabf5 - <unknown>
   4:     0x55c97aeac097 - <unknown>
   5:     0x55c97aeabe84 - <unknown>
   6:     0x55c97aeac54c - <unknown>
   7:     0x55c97aeac401 - <unknown>
   8:     0x55c97aeab216 - <unknown>
   9:     0x55c97aeac192 - <unknown>
  10:     0x55c97add6dd3 - <unknown>
  11:     0x55c97add6e63 - <unknown>
  12:     0x55c97ade9fa6 - <unknown>
  13:     0x55c97adfc8af - <unknown>
  14:     0x55c97ae8c03b - <unknown>
  15:     0x55c97ae8da68 - <unknown>
  16:     0x7fc3d37aaf19 - <unknown>
  17:     0x7fc3d38092b7 - <unknown>
  18:     0x7fc3d37a9112 - g_main_context_iteration
  19:     0x7fc3d2b06af6 - g_application_run
  20:     0x55c97ade28ac - <unknown>
  21:     0x55c97ae0dc05 - <unknown>
  22:     0x55c97adeb0fb - <unknown>
  23:     0x55c97ade3a83 - <unknown>
  24:     0x55c97adf982d - <unknown>
  25:     0x55c97aea3555 - <unknown>
  26:     0x55c97adeeb85 - <unknown>
  27:     0x7fc3d275acd0 - <unknown>
  28:     0x7fc3d275ad8a - __libc_start_main
  29:     0x55c97add74d5 - <unknown>
  30:                0x0 - <unknown>
thread 'main' panicked at 'The runtime of the component was shutdown. Maybe you accidentally dropped a controller?: Resize(Vec2D { x: 500.0, y: 500.0 })', /home/gabm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/relm4-0.6.2/src/channel/component.rs:66:34
stack backtrace:
   0:     0x55c97aeaade1 - <unknown>
   1:     0x55c97aecd25f - <unknown>
   2:     0x55c97aea89a1 - <unknown>
   3:     0x55c97aeaabf5 - <unknown>
   4:     0x55c97aeac097 - <unknown>
   5:     0x55c97aeabe84 - <unknown>
   6:     0x55c97aeac54c - <unknown>
   7:     0x55c97aeac447 - <unknown>
   8:     0x55c97aeab216 - <unknown>
   9:     0x55c97aeac192 - <unknown>
  10:     0x55c97add6dd3 - <unknown>
  11:     0x55c97add7213 - <unknown>
  12:     0x55c97ade0a5b - <unknown>
  13:     0x7fc3d2ca923e - <unknown>
  14:     0x7fc3d38d0b73 - <unknown>
  15:     0x7fc3d38d0c77 - g_signal_emit_valist
  16:     0x7fc3d38d0d34 - g_signal_emit
  17:     0x7fc3d2e6a158 - gtk_widget_allocate
  18:     0x7fc3d2cd3b63 - <unknown>
  19:     0x7fc3d2e69e81 - gtk_widget_allocate
  20:     0x7fc3d2dace54 - <unknown>
  21:     0x7fc3d2e69e81 - gtk_widget_allocate
  22:     0x7fc3d2e7de91 - <unknown>
  23:     0x7fc3d2e6a158 - gtk_widget_allocate
  24:     0x7fc3d2e7b978 - <unknown>
  25:     0x7fc3d2dd309d - <unknown>
  26:     0x7fc3d2ca923e - <unknown>
  27:     0x7fc3d38d0b73 - <unknown>
  28:     0x7fc3d38d0c77 - g_signal_emit_valist
  29:     0x7fc3d38d0d34 - g_signal_emit
  30:     0x7fc3d38d0b73 - <unknown>
  31:     0x7fc3d38d0c77 - g_signal_emit_valist
  32:     0x7fc3d38d0d34 - g_signal_emit
  33:     0x7fc3d303463c - <unknown>
  34:     0x7fc3d37ac39e - <unknown>
  35:     0x7fc3d37aaf19 - <unknown>
  36:     0x7fc3d38092b7 - <unknown>
  37:     0x7fc3d37a9112 - g_main_context_iteration
  38:     0x7fc3d2b06af6 - g_application_run
  39:     0x55c97ade28ac - <unknown>
  40:     0x55c97ae0dc05 - <unknown>
  41:     0x55c97adeb0fb - <unknown>
  42:     0x55c97ade3a83 - <unknown>
  43:     0x55c97adf982d - <unknown>
  44:     0x55c97aea3555 - <unknown>
  45:     0x55c97adeeb85 - <unknown>
  46:     0x7fc3d275acd0 - <unknown>
  47:     0x7fc3d275ad8a - __libc_start_main
  48:     0x55c97add74d5 - <unknown>
  49:                0x0 - <unknown>
```

**Comment by gabm** [comment]
Thank you for your report. I think we can at least catch the error properly and continue gracefully. I will have a look on that...

**Comment by gabm** [comment]
I pushed a bugfix as v0.1.1. Can you please confirm that the crash is gone?

**Comment by qdii** [comment]
I can confirm that the new version fixes the bug. It works fine now! Thank you so much :)

**Comment by gabm** [comment]
great! thanks for confirming
