### ISSUE TITLE
Segfault upon launching

### ISSUE THREAD

**Issue by svenstaro** [gabm/Satty#123]
I tried 0.14.0 as well as git. Running `satty -f Pictures/20240917_04h32m40s_grim.png` I get this:
```
(process:133577): Gtk-WARNING **: 05:39:30.273: Unknown key gtk-toolbar-style in /home/svenstaro/.config/gtk-4.0/settings.ini

(process:133577): Gtk-WARNING **: 05:39:30.273: Unknown key gtk-toolbar-icon-size in /home/svenstaro/.config/gtk-4.0/settings.ini

(process:133577): Gtk-WARNING **: 05:39:30.273: Unknown key gtk-button-images in /home/svenstaro/.config/gtk-4.0/settings.ini

(process:133577): Gtk-WARNING **: 05:39:30.273: Unknown key gtk-menu-images in /home/svenstaro/.config/gtk-4.0/settings.ini

(satty:133577): Adwaita-WARNING **: 05:39:30.291: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
zsh: segmentation fault (core dumped)  cargo run -- -f Pictures/20240917_04h32m40s_grim.png
```
Maybe it has something to do with the warnings? At any rate, this shouldn't segfault I reckon.

**Comment by gabm** [comment]
no that shouldn't happen.. can you try with another image file?

**Comment by svenstaro** [comment]
It crashes on any file. Here's a backtrace:
```
Thread 1 "satty" received signal SIGSEGV, Segmentation fault.
Downloading source file /usr/src/debug/mesa/build/../mesa-24.2.3/src/vulkan/wsi/wsi_common.c
wsi_GetPhysicalDeviceSurfaceCapabilitiesKHR () at ../mesa-24.2.3/src/vulkan/wsi/wsi_common.c:827
827	   struct wsi_interface *iface = wsi_device->wsi[surface->platform];
(gdb) bt
#0  wsi_GetPhysicalDeviceSurfaceCapabilitiesKHR () at ../mesa-24.2.3/src/vulkan/wsi/wsi_common.c:827
#1  0x00007ffff78a38b0 in gdk_vulkan_context_check_swapchain (context=0x555557016250,
    error=error@entry=0x7fffffffb9d0) at ../gtk/gdk/gdkvulkancontext.c:431
#2  0x00007ffff78a44ac in gdk_vulkan_context_surface_resized (draw_context=<optimized out>)
    at ../gtk/gdk/gdkvulkancontext.c:783
#3  0x00007ffff7827c4c in gdk_draw_context_surface_resized (context=<optimized out>)
    at ../gtk/gdk/gdkdrawcontext.c:250
#4  _gdk_surface_update_size (surface=0x55555611d5d0) at ../gtk/gdk/gdksurface.c:887
#5  gdk_wayland_surface_update_size (surface=surface@entry=0x55555611d5d0, width=<optimized out>,
    height=<optimized out>, scale=scale@entry=0x7fffffffba54) at ../gtk/gdk/wayland/gdksurface-wayland.c:272
#6  0x00007ffff782821d in gdk_wayland_surface_fractional_scale_preferred_scale_cb (data=0x55555611d5d0,
    fractional_scale=<optimized out>, scale=120) at ../gtk/gdk/wayland/gdksurface-wayland.c:836
#7  0x00007ffff5f4c596 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#8  0x00007ffff5f4900e in ffi_call_int (cif=cif@entry=0x7fffffffbc30, fn=<optimized out>,
    rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#9  0x00007ffff5f4bbd3 in ffi_call (cif=cif@entry=0x7fffffffbc30, fn=<optimized out>, rvalue=rvalue@entry=0x0,
    avalue=avalue@entry=0x7fffffffbd00) at ../src/x86/ffi64.c:710
#10 0x00007ffff61c88b0 in wl_closure_invoke (closure=closure@entry=0x555556422880, target=<optimized out>,
    target@entry=0x555556310aa0, opcode=opcode@entry=0, data=<optimized out>, flags=1)
    at ../wayland-1.23.1/src/connection.c:1228
#11 0x00007ffff61c9139 in dispatch_event (display=display@entry=0x5555560fdc40,
    queue=queue@entry=0x5555560fdd38) at ../wayland-1.23.1/src/wayland-client.c:1674
#12 0x00007ffff61c9553 in dispatch_queue (display=0x5555560fdc40, queue=0x5555560fdd38)
    at ../wayland-1.23.1/src/wayland-client.c:1820
#13 wl_display_dispatch_queue_pending (display=display@entry=0x5555560fdc40, queue=queue@entry=0x5555560fdd38)
    at ../wayland-1.23.1/src/wayland-client.c:2062
#14 0x00007ffff61cb1c4 in wl_display_dispatch_queue (display=<optimized out>, queue=<optimized out>)
    at ../wayland-1.23.1/src/wayland-client.c:2038
#15 0x00007ffff61cc4cc in wl_display_roundtrip_queue (display=0x5555560fdc40, queue=0x5555560fdd38)
    at ../wayland-1.23.1/src/wayland-client.c:1448
#16 0x00007ffff7833f24 in gdk_wayland_vulkan_context_create_surface (context=0x555557016250,
    vr_surface=0x555557016190) at ../gtk/gdk/wayland/gdkvulkancontext-wayland.c:48
#17 0x00007ffff78a5f29 in gdk_vulkan_context_real_init (initable=0x555557016250, cancellable=<optimized out>,
    error=0x7fffffffc1c0) at ../gtk/gdk/gdkvulkancontext.c:855
#18 0x00007ffff716eca0 in g_initable_new_valist (object_type=<optimized out>,
    first_property_name=0x7ffff79ee9bb "surface", var_args=var_args@entry=0x7fffffffbff0,
    cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffc1c0) at ../glib/gio/ginitable.c:249
#19 0x00007ffff716ed8c in g_initable_new (object_type=<optimized out>, cancellable=cancellable@entry=0x0,
    error=error@entry=0x7fffffffc1c0, first_property_name=<optimized out>) at ../glib/gio/ginitable.c:163
#20 0x00007ffff78ea6a3 in gdk_display_create_vulkan_context (self=0x555556103cc0, surface=0x55555611d5d0,
    error=0x7fffffffc1c0) at ../gtk/gdk/gdkdisplay.c:1336
#21 gsk_vulkan_renderer_create_context (renderer=0x55555701ec00, display=0x555556103cc0,
    surface=0x55555611d5d0, supported=0x7fffffffc124, error=0x7fffffffc1c0)
    at ../gtk/gsk/gpu/gskvulkanrenderer.c:93
#22 0x00007ffff792c8e9 in gsk_gpu_renderer_realize (renderer=0x55555701ec00, display=0x555556103cc0,
    surface=0x55555611d5d0, error=0x7fffffffc1c0) at ../gtk/gsk/gpu/gskgpurenderer.c:217
#23 0x00007ffff78b6ce3 in gsk_renderer_do_realize (renderer=renderer@entry=0x55555701ec00,
    display=0x555556103cc0, surface=0x55555611d5d0, error=0x7fffffffc1c0) at ../gtk/gsk/gskrenderer.c:272
#24 0x00007ffff78bdf68 in gsk_renderer_realize (renderer=renderer@entry=0x55555701ec00,
    surface=surface@entry=0x55555611d5d0, error=error@entry=0x7fffffffc1c0) at ../gtk/gsk/gskrenderer.c:325
#25 0x00007ffff78be0fc in gsk_renderer_new_for_surface (surface=0x55555611d5d0) at ../gtk/gsk/gskrenderer.c:782
#26 0x00007ffff7694171 in gtk_window_realize (widget=0x5555561f8a20) at ../gtk/gtk/gtkwindow.c:4304
#27 0x00007ffff7e42e1c in _g_closure_invoke_va (closure=0x5555561f16d0, return_value=0x0,
    instance=0x5555561f8a20, args=0x7fffffffc490, n_params=0, param_types=0x0) at ../glib/gobject/gclosure.c:896
#28 signal_emit_valist_unlocked (instance=instance@entry=0x5555561f8a20, signal_id=signal_id@entry=68,
    detail=detail@entry=0, var_args=var_args@entry=0x7fffffffc490) at ../glib/gobject/gsignal.c:3423
#29 0x00007ffff7e42f32 in g_signal_emit_valist (instance=0x5555561f8a20, signal_id=68, detail=0,
    var_args=var_args@entry=0x7fffffffc490) at ../glib/gobject/gsignal.c:3262
#30 0x00007ffff7e42ff4 in g_signal_emit (instance=instance@entry=0x5555561f8a20, signal_id=<optimized out>,
    detail=detail@entry=0) at ../glib/gobject/gsignal.c:3582
#31 0x00007ffff767066a in gtk_widget_realize (widget=0x5555561f8a20) at ../gtk/gtk/gtkwidget.c:3448
#32 0x00007ffff768c7c4 in gtk_window_show (widget=0x5555561f8a20) at ../gtk/gtk/gtkwindow.c:3854
#33 0x00007ffff7e2182a in g_closure_invoke (closure=0x5555561fc370, return_value=0x0, n_param_values=1,
    param_values=0x7fffffffc790, invocation_hint=0x7fffffffc6e0) at ../glib/gobject/gclosure.c:833
#34 0x00007ffff7e526a2 in signal_emit_unlocked_R.isra.0 (node=node@entry=0x7fffffffc880, detail=detail@entry=0,
    instance=instance@entry=0x5555561f8a20, emission_return=emission_return@entry=0x0,
    instance_and_params=instance_and_params@entry=0x7fffffffc790) at ../glib/gobject/gsignal.c:3720
#35 0x00007ffff7e42ca9 in signal_emit_valist_unlocked (instance=instance@entry=0x5555561f8a20,
    signal_id=signal_id@entry=64, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffc9f0)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../glib/gobject/gsignal.c:3519
#36 0x00007ffff7e42f32 in g_signal_emit_valist (instance=0x5555561f8a20, signal_id=64, detail=0,
    var_args=var_args@entry=0x7fffffffc9f0) at ../glib/gobject/gsignal.c:3262
#37 0x00007ffff7e42ff4 in g_signal_emit (instance=instance@entry=0x5555561f8a20, signal_id=<optimized out>,
    detail=detail@entry=0) at ../glib/gobject/gsignal.c:3582
#38 0x00007ffff76719fc in gtk_widget_show (widget=0x5555561f8a20) at ../gtk/gtk/gtkwidget.c:2724
#39 0x00005555557cf327 in gtk4::auto::widget::WidgetExt::set_visible<gtk4::auto::window::Window> (
    self=0x7fffffffcb48, visible=true)
    at /home/svenstaro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.8.2/src/auto/widget.rs:1370
#40 0x000055555582f3ff in relm4::app::{impl#0}::run::{closure#1}<satty::AppInput, satty::App> (
    app=0x7fffffffcba8)
    at /home/svenstaro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/relm4-0.8.1/src/app.rs:156
#41 0x00005555556224a7 in gio::auto::application::ApplicationExt::connect_activate::activate_trampoline<gtk4::auto::application::Application, relm4::app::{impl#0}::run::{closure_env#1}<satty::AppInput, satty::App>> (
    this=0x5555560eb4f0, f=0x5555561a33e0)
    at /home/svenstaro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.8/src/auto/application.rs:458
#42 0x00007ffff7e2182a in g_closure_invoke (closure=0x5555561a14b0, return_value=0x0, n_param_values=1,
    param_values=0x7fffffffcdb0, invocation_hint=0x7fffffffcd00) at ../glib/gobject/gclosure.c:833
#43 0x00007ffff7e52565 in signal_emit_unlocked_R.isra.0 (node=node@entry=0x7fffffffcea0, detail=detail@entry=0,
    instance=instance@entry=0x5555560eb4f0, emission_return=emission_return@entry=0x0,
    instance_and_params=instance_and_params@entry=0x7fffffffcdb0) at ../glib/gobject/gsignal.c:3887
#44 0x00007ffff7e42ca9 in signal_emit_valist_unlocked (instance=instance@entry=0x5555560eb4f0,
    signal_id=signal_id@entry=8, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffd010)
    at ../glib/gobject/gsignal.c:3519
#45 0x00007ffff7e42f32 in g_signal_emit_valist (instance=0x5555560eb4f0, signal_id=8, detail=0,
    var_args=var_args@entry=0x7fffffffd010) at ../glib/gobject/gsignal.c:3262
#46 0x00007ffff7e42ff4 in g_signal_emit (instance=instance@entry=0x5555560eb4f0, signal_id=<optimized out>,
    detail=detail@entry=0) at ../glib/gobject/gsignal.c:3582
#47 0x00007ffff71d5098 in g_application_activate (application=0x5555560eb4f0) at ../glib/gio/gapplication.c:2454
#48 0x00007ffff71d89a1 in g_application_real_local_command_line (application=0x5555560eb4f0,
    arguments=0x7fffffffd178, exit_status=0x7fffffffd174) at ../glib/gio/gapplication.c:1188
#49 0x00007ffff71d8b47 in g_application_run (application=0x5555560eb4f0, argc=<optimized out>,
    argv=0x555556123640) at ../glib/gio/gapplication.c:2684
#50 0x00005555557e93fe in gio::application::ApplicationExtManual::run_with_args<gtk4::auto::application::Application, alloc::string::String> (self=0x7fffffffd2e8, args=...)
    at /home/svenstaro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.8/src/application.rs:29
#51 0x000055555582f1e6 in relm4::app::RelmApp<satty::AppInput>::run<satty::AppInput, satty::App> (self=...,
    payload=...)
    at /home/svenstaro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/relm4-0.8.1/src/app.rs:163
#52 0x00005555558341f0 in satty::run_satty () at src/main.rs:320
#53 0x0000555555834381 in satty::main () at src/main.rs:330
```

**Comment by The-Lost-Light** [comment]
I update my GTK4 >= 4.15 then it crash on Arch linux.(4.14.5 work)

**Comment by gabm** [comment]
then it's a gtk bug in arch or an incompatibility between our used version of gtk-rs and gtk on arch.. not sure

**Comment by The-Lost-Light** [comment]
Yes, it look like its a gtk problem
https://github.com/hyprwm/Hyprland/issues/7854

**Comment by svenstaro** [comment]
Thanks for linking this. I'll take it up the chain!
